spring:
  datasource:
    username: wkollhfx
    url: jdbc:postgresql://salt.db.elephantsql.com:5432/wkollhfx
    password: jhNnFll0Gt_NS45IfqMIOwV-LkeikQfP
  jpa:
    database: POSTGRESQL
    defer-datasource-initialization: 'true'
    show-sql: 'false'
    hibernate:
      ddl-auto: none
  database:
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres
